# library/php/config.yml
project:
  org: library
  name: php

version_source:
  type: script
  script: get_versions.sh

variants:
  - name: "debian"
    template: "Dockerfile-debian-cli.template"
    tags:
      - "{version}"
      - "{minor_version}"
      - "latest"
  - name: "debian-apache"
    template: "Dockerfile-debian-apache.template"
    tags:
      - "{version}-apache"
      - "{minor_version}-apache"
  - name: "debian-fpm"
    template: "Dockerfile-debian-fpm.template"
    tags:
      - "{version}-fpm"
      - "{minor_version}-fpm"
  - name: "debian-zts"
    template: "Dockerfile-debian-zts.template"
    tags:
      - "{version}-zts"
      - "{minor_version}-zts"
  - name: "alpine"
    template: "Dockerfile-alpine-cli.template"
    tags:
      - "{version}-alpine"
      - "{minor_version}-alpine"
  - name: "alpine-fpm"
    template: "Dockerfile-alpine-fpm.template"
    tags:
      - "{version}-alpine-fpm"
      - "{minor_version}-alpine-fpm"
  - name: "alpine-zts"
    template: "Dockerfile-alpine-zts.template"
    tags:
      - "{version}-alpine-zts"
      - "{minor_version}-alpine-zts"
