# library/golang/config.yml
project:
  org: library
  name: golang

version_source:
  type: script
  script: get_versions.sh

variants:
  - name: "forky"
    template: "Dockerfile-forky.template"
    tags:
      - "{version}"
      - "{version}-forky"
      - "latest"
  - name: "alpine3.22"
    template: "Dockerfile-alpine.template"
    tags:
      - "{version}-alpine"
      - "{version}-alpine3.22"
  - name: "alpine3.23"
    template: "Dockerfile-alpine.template"
    tags:
      - "{version}-alpine3.23"

push:
  registry: "lcr.loongnix.cn"
  repository: "library/golang"
