# library/rust/config.yml
project:
  org: library
  name: rust

version_source:
  type: script
  script: get_versions.sh

variants:
  - name: "debian"
    template: "Dockerfile-debian.template"
    tags:
      - "{version}"
      - "{minor_version}"
      - "latest"
  - name: "debian-slim"
    template: "Dockerfile-debian-slim.template"
    tags:
      - "{version}-slim"
  - name: "alpine"
    template: "Dockerfile-alpine.template"
    tags:
      - "{version}-alpine"
      - "{minor_version}-alpine"
