# library/alpine/config.yml
project:
  org: library
  name: alpine

version_source:
  type: script
  script: get_versions.sh

variants:
  - name: "alpine"
    template: "Dockerfile-alpine.template"
    tags:
      - "{major_version}"
      - "{minor_version}"
      - "{version}"
      - "latest"
