# library/node/config.yml
project:
  org: library
  name: node

version_source:
  type: script
  script: get_versions.sh

variants:
  - name: "debian"
    template: "Dockerfile-debian.template"
    tags:
      - "{version}"
      - "{version}-debian"
      - "latest"
  - name: "debian-slim"
    template: "Dockerfile-debian-slim.template"
    tags:
      - "{version}-slim"
      - "{version}-debian-slim"
#  - name: "alpine"
#    template: "Dockerfile-alpine.template"
#    tags:
#      - "{version}-alpine"

push:
  registry: "lcr.loongnix.cn"
  repository: "library/node"
