# library/debian/config.yml
project:
  org: library
  name: debian

version_source:
  type: script
  script: get_versions.sh

variants:
  - name: "standard"
    template: "Dockerfile-standard.template"
    tags:
      - "{version}"
      - "latest"
  - name: "slim"
    template: "Dockerfile-slim.template"
    tags:
      - "{version}-slim"

push:
  registry: "lcr.loongnix.cn"
  repository: "library/debian"
