# library/httpd/config.yml
project:
  org: library
  name: httpd

version_source:
  type: script
  script: get_versions.sh

variants:
  - name: "debian"
    template: "Dockerfile-debian.template"
    tags:
      - "{version}"
      - "{version}-debian"
      - "latest"
  - name: "alpine"
    template: "Dockerfile-alpine.template"
    tags:
      - "{version}-alpine"
